function [x,y,xa,ya] = cutpolyconvert(lat,lon,p)
% CUTPOLYCONVERT - splits polygons between octants for Waterman projections
%
%   [x,y,xa,ya] = cutpolyconvert(lat,lon,p) adds a nan value between
%   (lat,lon) coordinates that cross an octahedral edge to prevent plotting
%   artifacts.

lat = lat(:);
lon = lon(:);

% cut polygons so coastlines don't create artifacts
ind = (0 < lat(1:end-1) & lat(2:end) < 0) | ...
    (0 > lat(1:end-1) & lat(2:end) > 0) | ...
    (-180-p.Results.Shift < lon(1:end-1) & lon(2:end) < -180-p.Results.Shift) | ...
    (-180-p.Results.Shift > lon(1:end-1) & lon(2:end) > -180-p.Results.Shift) | ...
    (-90-p.Results.Shift < lon(1:end-1) & lon(2:end) < -90-p.Results.Shift) | ...
    (-90-p.Results.Shift > lon(1:end-1) & lon(2:end) > -90-p.Results.Shift) | ...
    (0-p.Results.Shift < lon(1:end-1) & lon(2:end) < 0-p.Results.Shift) | ...
    (0-p.Results.Shift > lon(1:end-1) & lon(2:end) > 0-p.Results.Shift) | ...
    (90-p.Results.Shift < lon(1:end-1) & lon(2:end) < 90-p.Results.Shift) | ...
    (90-p.Results.Shift > lon(1:end-1) & lon(2:end) > 90-p.Results.Shift) | ...
    (180-p.Results.Shift < lon(1:end-1) & lon(2:end) < 180-p.Results.Shift) | ...
    (180-p.Results.Shift > lon(1:end-1) & lon(2:end) > 180-p.Results.Shift);

if p.Results.Inset
    ind = ind | lat(1:end-1) == -60;
end

%  convert to octahedral coordinates
[x,y,xa,ya] = OctahedralProjection(lat,lon, ...
    'Projection',p.Results.Projection, ...
    'Style',p.Results.Style, ...
    'Shift',p.Results.Shift, ...
    'Inset',p.Results.Inset, ...
    'MaxLat',p.Results.MaxLat);

ind = flipud(find(ind));

for i = 1:length(ind)
    x(ind(i)+1:end+1) = [NaN; x(ind(i)+1:end)];
    y(ind(i)+1:end+1) = [NaN; y(ind(i)+1:end)];
end

return